export const db = {
  vehicles: [
    {
      id: 1,
      licensePlate: 'ABC-1234',
      make: 'Toyota',
      model: 'Corolla',
      year: 2020,
      type: 'Car',
      status: 'active',
      location: 'Paris, France',
      driver: 'Veronica Herman',
      lastServiceDate: '2024-05-10',
      warnings: 'No Warnings',
      progress: 80
    },
    {
      id: 2,
      licensePlate: 'XYZ-5678',
      make: 'Ford',
      model: 'Transit',
      year: 2019,
      type: 'Van',
      status: 'maintenance',
      location: 'Berlin, Germany',
      driver: 'Frank Jones',
      lastServiceDate: '2024-04-22',
      warnings: 'Oil Change Needed',
      progress: 40
    },
    {
      id: 3,
      licensePlate: 'JKL-9101',
      make: 'Mercedes',
      model: 'Sprinter',
      year: 2021,
      type: 'Van',
      status: 'inactive',
      location: 'Madrid, Spain',
      driver: 'Helen Jacobs',
      lastServiceDate: '2024-03-15',
      warnings: 'No Warnings',
      progress: 0
    },
    {
      id: 4,
      licensePlate: 'MNO-2345',
      make: 'Renault',
      model: 'Kangoo',
      year: 2018,
      type: 'Van',
      status: 'active',
      location: 'Rome, Italy',
      driver: 'William Miller',
      lastServiceDate: '2024-06-01',
      warnings: 'Brake Pads Worn',
      progress: 65
    },
    {
      id: 5,
      licensePlate: 'PQR-6789',
      make: 'Volkswagen',
      model: 'Crafter',
      year: 2022,
      type: 'Truck',
      status: 'active',
      location: 'Amsterdam, Netherlands',
      driver: 'Barry Schowalter',
      lastServiceDate: '2024-05-20',
      warnings: 'No Warnings',
      progress: 90
    },
    {
      id: 6,
      licensePlate: 'STU-3456',
      make: 'Peugeot',
      model: 'Boxer',
      year: 2020,
      type: 'Van',
      status: 'maintenance',
      location: 'Brussels, Belgium',
      driver: 'Edward Smith',
      lastServiceDate: '2024-04-10',
      warnings: 'Engine Check',
      progress: 30
    },
    {
      id: 7,
      licensePlate: 'VWX-7890',
      make: 'Fiat',
      model: 'Ducato',
      year: 2017,
      type: 'Van',
      status: 'active',
      location: 'Vienna, Austria',
      driver: 'Charles Anderson',
      lastServiceDate: '2024-05-05',
      warnings: 'No Warnings',
      progress: 75
    },
    {
      id: 8,
      licensePlate: 'YZA-1235',
      make: 'Citroen',
      model: 'Jumper',
      year: 2021,
      type: 'Van',
      status: 'inactive',
      location: 'Zurich, Switzerland',
      driver: 'Myrtle Ullrich',
      lastServiceDate: '2024-02-28',
      warnings: 'Battery Low',
      progress: 0
    }
  ]
}
